### ISSUE TITLE
cuda 10.2  cublas error

### ISSUE THREAD

**Issue by xusk** [grimoire/amirstan_plugin#11]
cuda 10.2  OSError: /xhzy/amirstan_plugin/build/lib/libamirstan_plugin.so: undefined symbol: cublasCreate_v2

**Comment by grimoire** [comment]
Hi
I have meet some error about cublas in cuda10.2. Install cuda10.2 patch solved my problem. Not sure if it works on you.
read https://forums.developer.nvidia.com/t/matrixmultiply-failed-on-tensorrt-7-2-1/158187/5 for more detail.

**Comment by xusk** [comment]
ths
